.SH git\-webkit2png
.PP
A bunch of simple scripts to make using webkit2png in a git project
.PD 0
.P
.PD
easier.
.SS Requirements
.IP \[bu] 2
webkit2png
.SS Config
.SS webkit2png.urlsCommand
.PP
A command to generate URLs to run with webkit2png.
.SS webkit2png.selector
.PP
A selector to pass to webkit2png.
.SS webkit2png.post
.PP
Something to run after generating screenshots
.SS Usage
.PP
git webkit2png [clean | run | REF]
