#!/bin/bash
if [[ ! -z $1 ]]; then
  while [[ $1 = ?* ]]; do
      case $1 in
          -h|--help)
              git --help webkit2png
              exit 0
              ;;
          clean)
              git-webkit2png-clean.sh
              exit 0
              ;;
          run)
              git-webkit2png-run.sh
              exit 0
              ;;

          *)
              currentBranch=$(git rev-parse --abbrev-ref HEAD)
              currentRef=$(git rev-parse HEAD)
              git checkout $1
              git-webkit2png-run.sh
              givenRef=$(git rev-parse HEAD)
              git checkout $currentBranch
              git-webkit2png-run.sh
              git-webkit2png-diff.sh $currentRef $givenRef
              exit 0
              ;;
      esac

  shift
  done
else
  git-webkit2png-run.sh
fi
